[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "pallas-playground"
startCommand = "node backend/server.js"
[[services.ports]]
port = 3000
protocol = "http"
